;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Cooldown.Dash",DevComment="")
+GameplayTagList=(Tag="Cooldown.EnergyBolt",DevComment="")
+GameplayTagList=(Tag="Cooldown.HealingBolt",DevComment="")
+GameplayTagList=(Tag="Data.Damage",DevComment="")
+GameplayTagList=(Tag="Data.Heal",DevComment="")
+GameplayTagList=(Tag="Event.Abilities.Changed",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Attack.EnergyBolt",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Movement.Dash",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Support.HealingBolt",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Damage.Burst",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Dash",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Dash.Active",DevComment="")
+GameplayTagList=(Tag="GameplayCue.EnergyBolt.Active",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Heal.Burst",DevComment="")
+GameplayTagList=(Tag="GameplayCue.HealingBolt.Active",DevComment="")
+GameplayTagList=(Tag="Input.Ability.Dash",DevComment="Dash input binding tag")
+GameplayTagList=(Tag="Input.Ability.HealingBolt",DevComment="HealingBolt skill input binding tag")
+GameplayTagList=(Tag="Input.Ability.EnergyBolt",DevComment="EnergyBolt skill input binding tag")
+GameplayTagList=(Tag="Status.HP.Heal",DevComment="")
+GameplayTagList=(Tag="Status.Stamina.Regen",DevComment="")

